### PR TITLE
Patch iterator walking past end

### LINKED ISSUE #139: Debug Warning: Cannot increment string_view iterator past end
The unrolled loop isn't bounds checking the input string, allowing a regex like:
```
sometest
```
to walk off the end of the array if the input string is smaller.
```c
template <typename CharT, typename Iterator, typename EndIterator> constexpr CTRE_FORCE_INLINE bool compare_character(CharT c, Iterator & it, const EndIterator & end) {
	bool same = ((it != end) && (*it == c));
	++it; //problem line
	return same;
}

template <auto... String, size_t... Idx, typename Iterator, typename EndIterator> constexpr CTRE_FORCE_INLINE string_match_result<Iterator> evaluate_match_string(Iterator current, [[maybe_unused]] const EndIterator end, std::index_sequence<Idx...>) noexcept {

	bool same = (compare_character(String, current, end) && ... && true);

	return {current, same};
}

template <typename R, typename Iterator, typename EndIterator, auto... String, typename... Tail> 
constexpr CTRE_FORCE_INLINE R evaluate(const Iterator begin, Iterator current, const EndIterator end, [[maybe_unused]] const flags & f, R captures, ctll::list<string<String...>, Tail...>) noexcept {
	auto result = evaluate_match_string<String...>(current, end, std::make_index_sequence<sizeof...(String)>());
	
	if (!result.match) {
		return not_matched;
	}
	
	return evaluate(begin, result.position, end, consumed_something(f, sizeof...(String) > 0), captures, ctll::list<Tail...>());
}
```
Potential fix: check remaining distance between the current iterator and the end, eg much like string_view comparisons do a size check at the start. Probably better to customize for random access iterators. Or do a bit of reworking the fold expression to only bump the iterator forward and increase a "match count" which can be checked at the end.
EG: something like
```c
template <typename CharT, typename Iterator, typename EndIterator> constexpr CTRE_FORCE_INLINE size_t compare_character(CharT c, Iterator & it, const EndIterator & end, size_t match_count = 0) {
	size_t bump = ((it != end) && (*it == c));
        if (bump)
            ++it;        
	return match_count+=bump;
}
template <auto... String, size_t... Idx, typename Iterator, typename EndIterator> constexpr CTRE_FORCE_INLINE string_match_result<Iterator> evaluate_match_string(Iterator current, [[maybe_unused]] const EndIterator end, std::index_sequence<Idx...>) noexcept {
	size_t match_count = 0;
        (match_count = compare_character(String, current, end, match_count) && ... && true);
	return {current, match_count == sizeof...(String)};
}
```
Or...even more simply:
```c
template <typename CharT, typename Iterator, typename EndIterator> constexpr CTRE_FORCE_INLINE bool compare_character(CharT c, Iterator & it, const EndIterator & end) {
	bool same = ((it != end) && (*it == c));
	if (same)
		++it;
	return same;
}
```

### PR DESCRIPTION
**Pull request by Andersama**
Resolves #139

### CODE REVIEW

**Comment by hanickadot** [comment]
Thank you for pointing at this issue!

**Comment by Andersama** [comment]
Had the misfortune of sending a commit that didn't pass tests at first, likely because msvc is including extra headers. I was trying to express the bump to the pointer mathematically. Hopefully to let the compiler make it branch-less. Think this'd also do the trick, does use the ternary operator, which I know isn't pretty.

```c
	bool same = ((it != end) && (*it == c));
	it = same ? it + 1 : it;
        return it;
```

**Comment by hanickadot** [comment]
that I fixed with `utf8_iterator::operator++(int)`

**Comment by Andersama** [comment]
Oh, that would make way more sense why things failed, I thought it was having issues because iterator_traits or something wasn't included, which I thought was odd. Forgot about utf8. Thanks.

**Pull request merged**
