### PR TITLE
Patch Security Vulnerability: Array to pointer decay creates calls with zero_terminated_string_end_iterator()

### PR DESCRIPTION
**Pull request by Andersama**
Added wrappers to catch some obvious usages, it may be worth it to delete others!

### CODE REVIEW

**Comment by hanickadot** [comment]
It breaks usage over string literals (as they contains ending `\0`) and if you allow the ending `\0` it won't work for C-arrays. Instead use `std::array` and there is existing specialisation for types with `.begin()` and `.end()`

**Comment by Andersama** [comment]
Well, the alternative approach would be to specialize this case with it's own specialized iterator, one which plays it safe with a known bounds? It's a bit of a mix to have `::std::array` and the C array it wraps to behave differently.

**Comment by hanickadot** [comment]
I'm not going to do double checks just for convenience. If you are using C array you are probably aware of dangers of iterating them, and you can always provide pair of iterators to it.

**Comment by Andersama** [comment]
Really wish there was a way to distinguish a string literal at compile time, because that's unfortunate.

**Comment by Andersama** [comment]
Well, best I can tell, since string literals are well formed, which means the null at the end takes an entire character. So I suppose an alternative is just to assume it's a call for literals and remove one character? Not sure how you'd feel about that.

**Comment by Andersama** [comment]
It looks as though, and I'm not entirely clear on the specification of basic_string_view, that it may do what we'd both want? EG: it may be safe to construct a basic_string_view<CharT> with N-1 (because literals have the null character). It says the string it's viewed over may contain the null character*.

If I try:
```c
const char8_t u8sa[4] = u8"a\0b";
static constexpr auto weird_utf8 = ctll::fixed_string(
	R"RGX([a]\x00[b])RGX"
);
auto a = ctre::match<weird_utf8>(u8sa);
```
It seems as though the array is length 4, the view it constructs reads `u8"a"`, so it appears to behave similarly to the zero_terminated call, but the range is specified?

**Comment by hanickadot** [comment]
`string_view` is doing `strlen` in it's constructor, which can be omitted if the length is known ahead

**Comment by Andersama** [comment]
Well I guess the question is what happens with char8_t / utf8, because that's variable length encoding. Is it assuming N characters or N bytes?

**Comment by Andersama** [comment]
@hanickadot I get you would rather not double check, perhaps it should be a preprocessor macro option like with MSVC's greedy workaround? I'd leave it such that the default option plays it safe.

**Pull request closed without merging**
