### PR TITLE
fix wchar_t size in fixed_string

### PR DESCRIPTION
**Pull request by ray-haeb**

### CODE REVIEW

**Comment by hanickadot** [comment]
I'm sorry, but I don't know what's your motivation and what are you trying to do here. Without it I can't discuss it or merge it.

**Comment by Alcaro** [comment]
Looks to me like the goal is making CTRE treat wchar_t as UTF-16 if it's two bytes, i.e. on Windows.

**Comment by hanickadot** [comment]
wchar_t is actually UCS-2 encoding which behaves one unit = one char, that's the reason it's the same branch as char32_t

**Comment by ray-haeb** [comment]
On Unix wchar_t normally represents utf-32. But on Windows it is utf-16. Your code based on the assumption that wchar_t always equals char32_t in size. I just changed it to equal char32_t if it is 32 bit or char16_t if it is 16 bit. Sorry, I thought the code would be self explaining.

**Comment by ray-haeb** [comment]
> wchar_t is actually UCS-2 encoding which behaves one unit = one char, that's the reason it's the same branch as char32_t

[https://en.cppreference.com/w/cpp/language/types]
> wchar_t - type for wide character representation (see wide strings). Required to be large enough to represent any supported character code point (32 bits on systems that support Unicode. **A notable exception is Windows, where wchar_t is 16 bits and holds UTF-16 code units) It has the same size, signedness, and alignment as one of the integer types, but is a distinct type.**

**Comment by ThePhD** [comment]
`wchar_t` on Windows is 16-bit units. When used with the Standard Library, it behaves as if it's the outdated, deprecated UCS-2 encoding because that's all it can do.

`wchar_t` on (recent) POSIX machines is 32-bit units. When used with the Standard Library, it behaves as if it's UTF32.

... _Except_ on certain other platforms when the locale is equal to `zh_TW` or `jp_JP`, where the `wchar_t` encoding changes to something like EUC-TW and EUC-JP. In which case, your pull request would also probably be wrong.

`wchar_t` is not just "utf16 or utf32". It's an implementation-defined encoding and the only guarantee the Standard makes is:

> Type wchar_­t is a distinct type whose values can represent distinct codes for all members of the
largest extended character set specified among the supported locales  
> - [http://eel.is/c++draft/basic.fundamental#5](http://eel.is/c++draft/basic.fundamental#5)

> [ Note: The type wchar_­t is able to represent all members of the execution wide-character set
(see [basic.fundamental]). — end note ]  
>- [http://eel.is/c++draft/lex.ccon#6](http://eel.is/c++draft/lex.ccon#6)

Interpreting each `wchar_t` as exactly one code unit is exactly what the Standard mandates how to handle it. Other interpretations try to accommodate reality, but that reality is against the Standard. 🤷‍♂

**Comment by Alcaro** [comment]
Sometimes wchar_t on Windows represents UCS-2, sometimes it's UTF-16, sometimes it's "it's supposed to be UTF-16, but we don't enforce it, so expect unpaired surrogates" (filenames).

Sometimes the programmer expects the UTF-16 treatment (it is the obvious and correct behavior), sometimes UCS-2 (JS regexes act like UCS-2, for backwards compatibility reasons; this is arguably a bug, but sometimes the programmer wants bug-compatibility).

It's a mess.

**Comment by ray-haeb** [comment]
Ok, if wchar_t really is ucs-2 and not utf-16 and in this context only string literals are used (no text from some external source (e.g. windows)) your solution probably is the better one. Sorry.

**Pull request closed without merging**
